"""empty message

Revision ID: 15af63f0f67e
Revises: 9c76e093b8c6
Create Date: 2020-11-14 17:15:41.950181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15af63f0f67e'
down_revision = '9c76e093b8c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_unique_constraint("unique_device_id", ['device_id'])

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_unique_constraint("unique_mrn", ['mrn'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint("unique_device_id", type_='unique')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_constraint("unique_mrn", type_='unique')

    # ### end Alembic commands ###
