"""Initial migration.

Revision ID: 9c76e093b8c6
Revises:
Create Date: 2020-11-12 12:18:02.353712

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '9c76e093b8c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_email', sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(), nullable=True))
        batch_op.add_column(sa.Column('google_token', sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(), nullable=True))
        batch_op.add_column(sa.Column('lifenumber', sqlalchemy_utils.types.encrypted.encrypted_type.EncryptedType(), nullable=True))

    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.create_foreign_key("fk_user_id", 'user', ['user'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint("unique_email", ['email'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint("unique_email", type_='unique')

    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_constraint("fk_user_id", type_='foreignkey')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('lifenumber')
        batch_op.drop_column('google_token')
        batch_op.drop_column('google_email')

    # ### end Alembic commands ###
